export const INCREMENT_DATA = 'INCREMENT_DATA'
export const DECREMENT_DATA = 'DECREMENT_DATA'

export const SIGN_USER = "SIGN_USER"
export const EMAIL_VARIFICATION ="EMAIL_VARIFICATION"
export const AUTH_LOGIN = "AUTH_LOGIN"